"""
Synthetic Dataset Generator Module
===================================
Academic AI Decision-Support Prototype

Generates >= 1,200 synthetic donor records with realistic relationships and
probabilistic response outcomes for training and testing the emergency blood
donor recommendation model.

DISCLAIMER:
All data generated by this module is purely synthetic/demo data for academic purposes.
No real patient or donor personal health information (PHI) is included.
"""

import os
import random
import sqlite3
from typing import Tuple, List, Dict
import numpy as np
import pandas as pd

# City coordinates reference table (Demo/Synthetic Regional Hubs in Sri Lanka)
CITY_COORDINATES: Dict[str, Tuple[float, float]] = {
    "Colombo": (6.9271, 79.8612),
    "Kandy": (7.2906, 80.6337),
    "Gampaha": (7.0840, 80.0098),
    "Kalutara": (6.5854, 79.9607),
    "Negombo": (7.2083, 79.8358),
    "Galle": (6.0329, 80.2168),
    "Kurunegala": (7.4863, 80.3623),
    "Matara": (5.9549, 80.5550),
    "Ratnapura": (6.6828, 80.4034),
    "Anuradhapura": (8.3114, 80.4037)
}

BLOOD_GROUPS: List[str] = ["O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-"]
# Realistic population distribution weights
BLOOD_GROUP_WEIGHTS: List[float] = [0.38, 0.07, 0.28, 0.05, 0.15, 0.03, 0.03, 0.01]

GENDERS: List[str] = ["Male", "Female"]
GENDER_WEIGHTS: List[float] = [0.52, 0.48]


def generate_synthetic_donors(
    num_records: int = 1400,
    seed: int = 42
) -> pd.DataFrame:
    """
    Generate synthetic donor records with non-linear, realistic probabilistic relationships.

    Parameters
    ----------
    num_records : int
        Number of synthetic donor records to create (default 1,400 >= 1,200).
    seed : int
        Random seed for reproducibility.

    Returns
    -------
    pd.DataFrame
        DataFrame with the 15 specified donor columns.
    """
    np.random.seed(seed)
    random.seed(seed)

    donor_ids = [f"D{i+1:04d}" for i in range(num_records)]
    
    # Blood group assignment
    blood_groups = np.random.choice(BLOOD_GROUPS, size=num_records, p=BLOOD_GROUP_WEIGHTS)
    
    # Age: Normal distribution bounded between 18 and 65 (legal donor age range)
    ages = np.clip(np.round(np.random.normal(32, 10, size=num_records)).astype(int), 18, 65)
    
    # Gender
    genders = np.random.choice(GENDERS, size=num_records, p=GENDER_WEIGHTS)
    
    # City assignment & coordinates with slight Gaussian jitter (~1-5 km)
    cities_list = list(CITY_COORDINATES.keys())
    city_weights = [0.30, 0.15, 0.15, 0.08, 0.08, 0.08, 0.06, 0.04, 0.03, 0.03]
    assigned_cities = np.random.choice(cities_list, size=num_records, p=city_weights)
    
    latitudes = []
    longitudes = []
    for city in assigned_cities:
        base_lat, base_lon = CITY_COORDINATES[city]
        lat_jitter = np.random.normal(0, 0.02)  # ~2.2 km std dev
        lon_jitter = np.random.normal(0, 0.02)
        latitudes.append(round(base_lat + lat_jitter, 4))
        longitudes.append(round(base_lon + lon_jitter, 4))
    
    # Availability: ~70% currently available
    available = np.random.choice([1, 0], size=num_records, p=[0.72, 0.28])
    
    # Historical donation metrics
    # donation_count between 1 and 25
    donation_counts = np.clip(np.random.geometric(p=0.25, size=num_records), 1, 25)
    
    # days_since_last_donation: 30 to 450 days (safe interval is typically >= 90 or 120 days)
    days_since_last = np.random.randint(30, 450, size=num_records)
    
    # previous_requests (number of times notified in past emergencies)
    previous_requests = np.clip(
        donation_counts + np.random.randint(1, 15, size=num_records),
        1, 35
    )
    
    # previous_responses (cannot exceed previous_requests)
    # Donors who donate frequently tend to respond more reliably
    raw_response_prop = np.clip(
        np.random.beta(a=3.5, b=2.0, size=num_records) * (0.5 + 0.5 * (donation_counts / 25.0)),
        0.05, 0.98
    )
    previous_responses = np.round(raw_response_prop * previous_requests).astype(int)
    previous_responses = np.clip(previous_responses, 0, previous_requests)
    
    # response_rate calculation
    response_rate = np.round(previous_responses / previous_requests, 2)
    
    # contacted_before (binary flag)
    contacted_before = np.where(previous_requests > 0, 1, 0)
    
    # Probabilistic generation of target_response (1 = likely to respond, 0 = unlikely)
    # Log-odds based on feature interactions + noise:
    # - Available status is a heavy positive (+1.8)
    # - High response rate (+2.5)
    # - Days since last donation (if >= 90 days, +0.8; if < 90, -1.2)
    # - Donation count (+0.08 per donation)
    # - Gaussian noise to ensure realistic ML classification task
    
    log_odds = (
        -2.0
        + (2.2 * available)
        + (3.0 * (response_rate - 0.5))
        + (0.06 * donation_counts)
        + np.where(days_since_last >= 90, 0.6, -1.5)
        + (0.4 * contacted_before)
        - (0.015 * (ages - 30))
        + np.random.normal(0, 0.75, size=num_records)  # Realistic stochastic noise
    )
    
    # Sigmoid function for probability
    probs = 1.0 / (1.0 + np.exp(-log_odds))
    target_response = (probs >= 0.50).astype(int)
    
    # Unavailable donors almost never respond (physical constraint override with 96% penalty)
    for i in range(num_records):
        if available[i] == 0 and np.random.rand() < 0.96:
            target_response[i] = 0

    df = pd.DataFrame({
        "donor_id": donor_ids,
        "blood_group": blood_groups,
        "age": ages,
        "gender": genders,
        "city": assigned_cities,
        "latitude": latitudes,
        "longitude": longitudes,
        "available": available,
        "donation_count": donation_counts,
        "days_since_last_donation": days_since_last,
        "previous_requests": previous_requests,
        "previous_responses": previous_responses,
        "response_rate": response_rate,
        "contacted_before": contacted_before,
        "target_response": target_response
    })

    return df


def generate_sample_emergency_requests() -> pd.DataFrame:
    """
    Generate sample emergency requests for testing and database initialization.
    """
    sample_requests = [
        {
            "request_id": "REQ-1001",
            "required_blood_group": "O+",
            "hospital": "National Hospital Colombo",
            "latitude": 6.9271,
            "longitude": 79.8612,
            "units_required": 2,
            "priority": "Critical",
            "request_date": "2026-09-15 08:30:00",
            "notes": "Emergency surgery for trauma patient in ICU"
        },
        {
            "request_id": "REQ-1002",
            "required_blood_group": "A-",
            "hospital": "Teaching Hospital Kandy",
            "latitude": 7.2906,
            "longitude": 80.6337,
            "units_required": 3,
            "priority": "High",
            "request_date": "2026-09-15 09:15:00",
            "notes": "Postpartum hemorrhage complication"
        },
        {
            "request_id": "REQ-1003",
            "required_blood_group": "B+",
            "hospital": "District General Hospital Gampaha",
            "latitude": 7.0840,
            "longitude": 80.0098,
            "units_required": 1,
            "priority": "Medium",
            "request_date": "2026-09-15 10:00:00",
            "notes": "Scheduled cardiac procedure"
        },
        {
            "request_id": "REQ-1004",
            "required_blood_group": "AB+",
            "hospital": "Teaching Hospital Karapitiya Galle",
            "latitude": 6.0329,
            "longitude": 80.2168,
            "units_required": 2,
            "priority": "Critical",
            "request_date": "2026-09-15 10:45:00",
            "notes": "Acute gastrointestinal bleeding"
        }
    ]
    return pd.DataFrame(sample_requests)


def save_and_init_db(data_dir: str = "data", db_path: str = "data/blood_donor.db") -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Generate datasets, save to CSV, and initialize SQLite database.
    """
    os.makedirs(data_dir, exist_ok=True)
    
    # 1. Generate synthetic donors (1,400 records)
    donors_df = generate_synthetic_donors(num_records=1400, seed=42)
    donors_csv_path = os.path.join(data_dir, "donors.csv")
    donors_df.to_csv(donors_csv_path, index=False)
    print(f" Saved {len(donors_df)} synthetic donor records to '{donors_csv_path}'")
    
    # 2. Generate sample requests
    requests_df = generate_sample_emergency_requests()
    requests_csv_path = os.path.join(data_dir, "emergency_requests.csv")
    requests_df.to_csv(requests_csv_path, index=False)
    print(f" Saved sample emergency requests to '{requests_csv_path}'")
    
    # 3. Create SQLite Database and tables
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    # Create donors table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS donors (
        donor_id TEXT PRIMARY KEY,
        blood_group TEXT NOT NULL,
        age INTEGER,
        gender TEXT,
        city TEXT,
        latitude REAL,
        longitude REAL,
        available INTEGER,
        donation_count INTEGER,
        days_since_last_donation INTEGER,
        previous_requests INTEGER,
        previous_responses INTEGER,
        response_rate REAL,
        contacted_before INTEGER,
        target_response INTEGER
    )
    """)
    
    # Create emergency_requests table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS emergency_requests (
        request_id TEXT PRIMARY KEY,
        required_blood_group TEXT NOT NULL,
        hospital TEXT NOT NULL,
        latitude REAL,
        longitude REAL,
        units_required INTEGER,
        priority TEXT,
        request_date TEXT,
        notes TEXT
    )
    """)
    
    # Create donation_history table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS donation_history (
        donation_id INTEGER PRIMARY KEY AUTOINCREMENT,
        donor_id TEXT,
        donation_date TEXT,
        response INTEGER,
        request_id TEXT,
        FOREIGN KEY (donor_id) REFERENCES donors (donor_id)
    )
    """)
    
    # Create predictions table
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS predictions (
        prediction_id INTEGER PRIMARY KEY AUTOINCREMENT,
        request_id TEXT,
        donor_id TEXT,
        response_probability REAL,
        recommendation_score REAL,
        recommendation_label TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (donor_id) REFERENCES donors (donor_id)
    )
    """)
    
    # Insert or replace donors into SQLite
    donors_df.to_sql("donors", conn, if_exists="replace", index=False)
    requests_df.to_sql("emergency_requests", conn, if_exists="replace", index=False)
    
    conn.commit()
    conn.close()
    print(f" Initialized SQLite database tables in '{db_path}'")
    
    return donors_df, requests_df


if __name__ == "__main__":
    save_and_init_db()
